French translation
npm/how-to-npm pull request #101
Opened 2017-02-02 19:22 UTC by cedced19

Add French translation.

It may have some misspelling because I was tired.

2017-02-02 19:34 UTC, watilde commented
That's brilliant! Kat and I also did it in another lang, but it's really hard to translate full sentences alone. Again, great job! Let's have some reviews and ship it ;)

2017-02-02 20:15 UTC, ungoldman requested changes
Reviewed with various spelling and phrasing corrections!

2017-02-02 20:15 UTC, ungoldman commented on i18n/fr.json
> +    "no_package": "Il semblerait que le fichier `package.json` soir manquant. Avez-vous lancer `npm init`?"
`soir` -> `soit`

2017-02-02 20:15 UTC, ungoldman commented on i18n/fr.json
> +    "whoami_err": "Uh oh!\nIl semblerait que quelque chose se soit mal passé.",
`se soit` -> `ce soit`

2017-02-02 20:15 UTC, ungoldman commented on i18n/fr.json
> +    "success": "Félicitations, {{user}}!\nVous êtes le fier propriétaire d'un nouveau compte npm imaginaire!\nFaites-en bon usage. Jamais dans la colère. Toujours pour le bien.\n\nAvec cette douce pu
`qu'il ne nous poursuivrons pas` -> `qu'il ne nous poursuivra pas`

2017-02-02 20:15 UTC, ungoldman commented on i18n/fr.json
> +    "section_missing": "Oops!  Vous n'avez pas de séction `scripts.test` dans votre\nfichier package.json file.  Éditez le, et essayez à nouveau.",
pas d'accent pour `séction`

`séction` -> `section`

2017-02-02 20:15 UTC, ungoldman commented on i18n/fr.json
> +    "error": "Uh oh!\nIl semble que vous n'avez pas publié le\n  package {{name}}\n.  Try again!"
`Try again!` -> `Essayez encore!`

2017-02-02 20:15 UTC, ungoldman commented on i18n/fr.json
> +    "current_missing": "Hmm... Je vois que vous avez publié plus d'une fois, mais\nla version actuelle ({{version}}) n'est pas comprise.\nVoici ce que je voix ici:\n{{{found}}}\nEssayez de plublier à
`plublier` -> `publier`

2017-02-02 20:15 UTC, ungoldman commented on i18n/fr.json
> +    "success": "Uh oh, il semblerait que vous avez seulement un simple dist-tag.\nUilisez `npm help dist-tag` pour apprendre comment en ajouter un autre."
`Uilisez` -> `Utilisez`

2017-02-02 20:15 UTC, ungoldman commented on i18n/fr.json
> +    "reset-registry": "RÉINITIALISATION DU RESISTRE"
`RESISTRE` -> `REGISTRE`

2017-02-02 20:15 UTC, ungoldman commented on problems/00-install-npm/problem.fr.txt
> +how-to-npm solution . Montrer la solution pour l'exercice en cours
`Montrer` -> `Montrez`

2017-02-02 20:15 UTC, ungoldman commented on problems/00-install-npm/skip.fr.txt
> +avec `sudo`or as en tant que administrateur.
> avec `sudo`or as en tant que administrateur.

change to 

> avec `sudo` ou en tant que administrateur.

2017-02-02 20:15 UTC, ungoldman commented on problems/01-dev-environment/success.fr.txt
> +Cela ne serait normalement pas nécessaire, mais l'atelier l'utilise.
remove `.`

2017-02-02 20:15 UTC, ungoldman commented on problems/02-login/problem.fr.txt
> +npm est meilleur quand vous pouvez faire partie de celui-ci.
awkward phrasing, maybe this would convey the meaning a little better:

> npm est meilleur quand vous en faites partie.

2017-02-02 20:15 UTC, ungoldman commented on problems/03-start-a-project/problem.fr.txt
> +Lancez `npm init --scope=<username>`, et replacez <username> avec
`replacez` -> `remplacez`

2017-02-02 20:15 UTC, ungoldman commented on problems/04-install-a-module/problem.fr.txt
> +Les dépendances sont récupéré depuis le registre, et dépaqueter dans le
`récupéré` -> `récupérés`

`dépaqueter` -> `dépaquetés`

2017-02-02 20:15 UTC, ungoldman commented on problems/05-listing-dependencies/continue.fr.txt
> +dans un objet appelé «dependancies». Cependant, lorsque nous avons
`dependancies` -> `dependencies`

2017-02-02 20:15 UTC, ungoldman commented on problems/05-listing-dependencies/continue.fr.txt
> +de faire cela lorsque vous essayez seulement une dépendance, mais quand vous
> Vous pourriez ne pas vouloir de faire cela lorsque vous essayez seulement une dépendance

awkward phrasing, maybe try

> Vous ne voudrez peut-être pas faire ça lorsque vous essayez seulement une dépendance

2017-02-02 20:15 UTC, ungoldman commented on problems/06-npm-test/problem.fr.txt
> +without throwing an error, or else the test fails.
text from english version is still here, needs to be deleted

2017-02-02 20:15 UTC, ungoldman commented on problems/06-npm-test/problem.fr.txt
> +Informations supplémentaires: Si vous vouliez effectivement exécuter des tests que
`vouliez effectivement` -> `voulez`

2017-02-02 20:15 UTC, ungoldman commented on problems/08-publish/problem.fr.txt
> +mais il n'y a aucune garantie gue personne ne l'a vu dans l'intervalle.)
`gue` -> `que`

2017-02-02 20:15 UTC, ungoldman commented on problems/16-finale/success.fr.txt
> +À plus tard sur internet !
`internet` -> `l'internet`

2017-02-02 20:15 UTC, ungoldman commented on problems/11-dist-tag/problem.fr.txt
> +Cependant, si vous avez besoin de publier quelque chose, et *ne pas* f
remove `f`

2017-02-03 16:01 UTC, cedced19 commented on problems/00-install-npm/problem.fr.txt
> +how-to-npm solution . Montrer la solution pour l'exercice en cours
Il y a effectivement une faute mais c'est plutôt `Vérifiez` -> `Vérifier` puisque se sont des infinitifs en anglais.

2017-02-03 17:42 UTC, ungoldman commented on problems/00-install-npm/problem.fr.txt
> +how-to-npm solution . Montrer la solution pour l'exercice en cours
juste!

2017-02-03 17:42 UTC, ungoldman commented
LGTM 👍

2017-02-05 17:09 UTC, watilde commented
Thank you so much following up courteously! @ungoldman 

Let's ship it then 😺

2017-02-05 17:09 UTC, merged

2017-02-05 17:19 UTC, watilde commented
This translation was released as `v2.3.0` 🎉 
```
$ npm info how-to-npm versions

[ '0.0.0',
  '1.0.0',
  '1.1.1',
  '1.2.0',
  '2.0.0',
  '2.1.0',
  '2.1.1',
  '2.1.2',
  '2.2.0',
  '2.2.1',
  '2.2.2',
  '2.3.0' ]
```

Merci beaucoup! Great work.