Improve French translations
npm/how-to-npm pull request #142
Opened 2018-12-04 11:07 UTC by jmpp

I noticed that some translations in French were not really significatives, so I felt free to improve them.

2018-12-06 20:21 UTC, watilde commented
@jmpp Oh thank you! Do you know someone who can review this...?

2019-10-23 13:49 UTC, jmpp commented
> @jmpp Oh thank you! Do you know someone who can review this...?

(I have missed your answer. Sorry about this)
Maybe @isaacs or @tdd could review this?

2022-03-28 04:10 UTC, juanpicado requested changes
You have changes the package name, why? It is a mistake?

2022-03-28 04:10 UTC, juanpicado commented on package.json
> +  "name": "@jmpp/how-to-npm",
🤔🤔🤔🤔🤔🤔🤔🤔

2022-03-28 07:50 UTC, closed without merging

2022-03-28 07:56 UTC, jmpp commented on package.json
> +  "name": "@jmpp/how-to-npm",
My bad! That's a wrong manipulation from yesterday.

**Explanations:**
I wanted to get an updated version with improved French translations from Dec 4th 2018, that still wasn't merged.

I took back my old repo, made some changes and updated the package's name in order to publish a scoped package : https://www.npmjs.com/package/@jmpp/how-to-npm for my students.

Working in a rush, I forgot to create another branch than `master` for this, so my "personal" updates came into this pull-request that was still waiting ...

As it's now not relevant anymore, I've hard-removed theses commits from `master`

2022-03-28 15:48 UTC, juanpicado commented on package.json
> +  "name": "@jmpp/how-to-npm",
Np thanks for providing details 🙌

2022-03-28 15:55 UTC, jmpp commented on package.json
> +  "name": "@jmpp/how-to-npm",
@juanpicado So, I did remove the original pull request that came with my "accidental" other commits.

But would you be interested in another clean PR with the original proposal of the improved French translations? :)