Add basic i18n support for problem text
npm/how-to-npm pull request #20
Opened 2015-04-18 20:09 UTC by watilde

Hi.
I added basic i18n support for **only** problem text. TBH also I wanted to add i18n support to verify but this commit has became a little bigger. So I'm glad if we think together how to progress this proposal.

Here is updates:
+ Switched to workshopper from adventure for i18n support
+ Separate problem text from JavaScript file of problem: [patch](https://gist.github.com/watilde/f201fb146b394bf53003)
+ Add i18n support for **only** problem text
+ Add translated text in Japanese

Thanks.

2016-08-20 23:35 UTC, martinheidegger commented
@watilde I would like to improve on this PR. Would it be okay to mark it as "work-in-progress"?

2016-10-18 08:27 UTC, watilde commented
@martinheidegger Yes, it's ok! I've added WIP tag into the title.

2016-10-18 08:41 UTC, martinheidegger requested changes
For the biggest part it looks okay to me. There are some things that could look smoother but basically it seems to work. A rebase to master would be good before I can do a technical test.

2016-10-18 08:41 UTC, martinheidegger commented on package.json
> +    "workshopper-adventure": "^3.4.1"
The latest workshopper is 5.0.3. It would be good to update it!

2016-10-18 08:41 UTC, martinheidegger commented on problems/dev-environment/index.js
> +  this.problem = function () {
Note: it is possible to specify a problem like: 

```
problem = {
  file: path.join(__dirname, 'problem.{lang}.txt')
}
```

but of course this means that you would need to rename the existing .txt files

2016-10-18 08:41 UTC, martinheidegger commented on problems/dist-tag-removal/problem.txt
> +*/}.toString().split('\n').slice(1,-1).join('\n')
This line seems to be added by mistake

2016-11-04 15:06 UTC, watilde commented on problems/dev-environment/index.js
> +  this.problem = function () {
That's good idea, but let me do it as a separated another patch to keep the diff more less

2016-11-04 15:52 UTC, watilde commented
@martinheidegger Hey Martin, I've rebased and got rid of translated problem texts to keep the diff more less

2016-11-07 16:25 UTC, watilde commented
Merged https://github.com/watilde/how-to-npm/pull/1

2016-11-07 19:26 UTC, martinheidegger commented
I added another PR to your branch with the missing exercises. Please also run npm test and fix standard formatting ^_^

2016-11-07 19:36 UTC, martinheidegger commented
For extra points:
1. It might be nice to move to markdown instead of text files?
2. In `/i18n/en.json` i put all the exercises in the root node but it would be better if they were one level deeper in `exercises`
3. Maybe it would be a good idea to add this to the workshopper definition? _(Would need textual updates)_

```javascript
    bg: 'white',
    fg: 'red'
  },
  header: require('workshopper-adventure/default/header'),
  footer: require('workshopper-adventure/default/footer'),
  commands: [{
```

2016-11-08 09:30 UTC, martinheidegger commented
Do you want to do more changes?

2016-11-08 10:12 UTC, watilde commented
@martinheidegger I've fixed the lint errors, and title names. Then let's do that!

2016-11-08 10:21 UTC, watilde commented
`start-a-project/index.js` was still old, and I've updated it. Verified.

2016-11-08 10:37 UTC, martinheidegger commented on menu.json
> +  "00 Install npm",
By changing this you should also change the i18n/en.json in which there are pointers to these names

2016-11-08 12:15 UTC, watilde commented on menu.json
> +  "00 Install npm",
That's right. I've updated the menu.json as well

2016-11-08 22:15 UTC, watilde commented
@martinheidegger Ok i've tried them all again. Added one fix https://github.com/workshopper/how-to-npm/pull/20/commits/bb111a69c2b6e3bcc183c822b22d8a03690cf1d7, and it worked fine eventually.

2016-11-08 22:35 UTC, martinheidegger commented
@workshopper/core LGTM: ship it?!

2016-11-09 01:29 UTC, martinheidegger approved these changes

2016-11-09 08:07 UTC, merged

2016-11-09 09:59 UTC, watilde commented
Heyy thanks JP and Martin!

2016-11-09 15:03 UTC, a0viedo commented
sorry for getting somewhat late, but great work @watilde @martinheidegger @jpwesselink  :tada: